development:
  clients:
    default:
      database: hotel_manager_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: hotel_manager_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
  options:
    raise_not_found_error: false
